name: Generación de código OpenAPI

on:
  push:
    branches: [ "main" ]

jobs:
  generar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generar servidor Python Flask desde OpenAPI
        run: |
          ls -la
          java -version
          # Genera el código a partir de api.yaml con el jar en la raíz
          java -jar openapi-generator-cli.jar generate -i api.yml -g python-flask -o ./openapi_server

      - name: Comprimir carpeta generada
        run: zip -r openapi_server.zip openapi_server

      - name: Subir artefacto ZIP
        uses: actions/upload-artifact@v4
        with:
          name: openapi_server
          path: openapi_server.zip
